#!/bin/bash

# Copyright 2013 Ricardo Tubio (rtpardavila@gmail.com)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

################################################################################
# Autor: rtpardavila[at]gmail.com
# Description: transforms a CSV file generated by the HUMSAT payload into a KML
#				file with the location of the sensors.
#
# Usage (quite straightforward): csv2kml.sh input.csv output.kml

#################################################################### functions()

function wrong_usage
{
	echo "[ERROR] Wrong usage ($#): $0 input.csv output.kml"
	exit -1
}

function input_not_found 
{
	echo "[ERROR] Input file has not been found, exiting..."
	exit -1
}
 
function output_exists
{
	export backup_file="$2.backup"
	echo "[WARNING] Output file already exists, moving it to <$backup_file>."
	mv -f $2 $backup_file
}

######################################################################### main()

export EVENT_FILTER='Event-E'
export FIELD_TIMESTAMP=40
export FIELD_SENSOR_ID=45
export FIELD_LEN=46
export FIELD_DATA=47

export HEADER="timestamp,sensorId,len,data"
export FIELDS=$FIELD_TIMESTAMP,$FIELD_SENSOR_ID,$FIELD_LEN,$FIELD_DATA

# 1) CLI arguments check:

[ $# -eq 2 ]  	|| wrong_usage 	
[ -f $1 ] 		|| input_not_found
[ -f $2 ] 		|| output_exists

# 2) Intermediate CSV file generation:

echo $HEADER > $2
cat $1 | grep $EVENT_FILTER | cut -d',' -f$FIELDS | sed -e 's/^,//g' >> $2

# 3) Data field processing:
export output_kml="$2.kml"
# java -jar SensorLocator.jar $2 $output_kml

